"""
This is a tool to perform general calculations with Kashiwara's Crystals
It can do the following computations:
* Build a Cartan matrix from its name only
* Build a crystal from Littelman's LS Paths
* perform tensor products of two crystals and draw the results on a grid against the input crystals
* Compute direct sums of crystals and saves the result as a new crystal
* Compute and visualize tensor products of arbitrary length of given crystals and decompose them into irreducibles with given highest weights. The result is saved in a separate pdf file
* (For Type A only) Build a monoidal category of crystals generated by canonical projections/inclusions/commutors of crystals and equipped with the natural associators and unitors
* Compute nested compositions/tensor products/linear combinations of morphisms of crystals and print what the morphism does to each node
Implemented by M. Alqady - Last updated April 2026
"""


import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import networkx as nx
from fractions import Fraction
import itertools
import math


# =====================================================================
# ALGEBRA & CRYSTAL NODES
# =====================================================================

class LieAlgebra:
    def __init__(self, cartan_type=None, cartan_matrix=None):
        if cartan_matrix is not None:
            self.type_name = cartan_type if cartan_type else "Custom"
            raw_matrix = cartan_matrix
        elif cartan_type is not None:
            self.type_name = cartan_type.upper().strip()
            raw_matrix = self._build_standard_matrix(self.type_name)
        else:
            raise ValueError("Provide either a cartan_type (e.g., 'A3') or a cartan_matrix.")

        self.matrix = [[Fraction(x) for x in row] for row in raw_matrix]
        self.rank = len(self.matrix)
        self.index_set = list(range(1, self.rank + 1))

    def _build_standard_matrix(self, type_name):
        letter = type_name[0]
        n = int(type_name[1:])
        matrix = [[0] * n for _ in range(n)]

        for i in range(n): matrix[i][i] = 2

        if letter in ['A', 'B', 'C']:
            for i in range(n - 1):
                matrix[i][i + 1] = -1
                matrix[i + 1][i] = -1
            if letter == 'B' and n >= 2:
                matrix[n - 2][n - 1] = -1
                matrix[n - 1][n - 2] = -2
            elif letter == 'C' and n >= 2:
                matrix[n - 2][n - 1] = -2
                matrix[n - 1][n - 2] = -1
        elif letter == 'D':
            for i in range(n - 2):
                matrix[i][i + 1] = -1
                matrix[i + 1][i] = -1
            matrix[n - 3][n - 1] = -1
            matrix[n - 1][n - 3] = -1
            matrix[n - 2][n - 1] = 0
            matrix[n - 1][n - 2] = 0
        elif letter == 'G' and n == 2:
            matrix = [[2, -3], [-1, 2]]
        else:
            raise ValueError(f"Type {type_name} not natively supported.")
        return matrix

    def alpha(self, i):
        return tuple(self.matrix[j][i - 1] for j in range(self.rank))

    def reflect(self, v, i):
        c = v[i - 1]
        a_i = self.alpha(i)
        return tuple(v[j] - c * a_i[j] for j in range(self.rank))

class CrystalNode:
    def wt(self): raise NotImplementedError

    def e(self, i): raise NotImplementedError

    def f(self, i): raise NotImplementedError

    def eps(self, i): raise NotImplementedError

    def phi(self, i): raise NotImplementedError

class LSPath(CrystalNode):
    def __init__(self, segments, algebra):
        self.algebra = algebra
        self.segments = self._clean(segments)

    def _clean(self, segments):
        if not segments: return ()
        cleaned = []
        curr_v, curr_l = segments[0]
        for v, l in segments[1:]:
            if l == Fraction(0): continue
            if v == curr_v:
                curr_l += l
            else:
                if curr_l > Fraction(0): cleaned.append((curr_v, curr_l))
                curr_v, curr_l = v, l
        if curr_l > Fraction(0): cleaned.append((curr_v, curr_l))
        return tuple(cleaned)

    def __hash__(self):
        return hash(self.segments)

    def __eq__(self, other):
        return isinstance(other, LSPath) and self.segments == other.segments

    def __repr__(self):
        w = self.wt()
        str_w = tuple(int(x) if x.denominator == 1 else float(x) for x in w)
        return f"{str_w}"

    def wt(self):
        w = [Fraction(0)] * self.algebra.rank
        for v, l in self.segments:
            for i in range(self.algebra.rank): w[i] += v[i] * l
        return tuple(w)

    def _height_data(self, i):
        h_curr, min_h = Fraction(0), Fraction(0)
        for v, l in self.segments:
            h_curr += v[i - 1] * l
            if h_curr < min_h: min_h = h_curr
        return h_curr, min_h

    def eps(self, i):
        return -self._height_data(i)[1]

    def phi(self, i):
        h_end, min_h = self._height_data(i)
        return h_end - min_h

    def f(self, i):
        h_curr = Fraction(0)
        H_list = [Fraction(0)]
        for v, l in self.segments:
            h_curr += v[i - 1] * l
            H_list.append(h_curr)

        m = min(H_list)
        if H_list[-1] - m < Fraction(1): return None

        k_0 = len(H_list) - 1 - H_list[::-1].index(m)
        new_segs = list(self.segments[:k_0])
        h_curr = m

        for idx in range(k_0, len(self.segments)):
            v, l = self.segments[idx]
            dh = v[i - 1] * l
            if h_curr + dh >= m + Fraction(1):
                dh_needed = m + Fraction(1) - h_curr
                l_refl = dh_needed / v[i - 1]
                v_refl = self.algebra.reflect(v, i)
                new_segs.append((v_refl, l_refl))
                new_segs.append((v, l - l_refl))
                new_segs.extend(self.segments[idx + 1:])
                break
            else:
                v_refl = self.algebra.reflect(v, i)
                new_segs.append((v_refl, l))
                h_curr += dh

        return LSPath(new_segs, self.algebra)

    def e(self, i):
        h_curr = Fraction(0)
        H_list = [Fraction(0)]
        for v, l in self.segments:
            h_curr += v[i - 1] * l
            H_list.append(h_curr)

        m = min(H_list)
        if m > Fraction(-1): return None

        k_1 = H_list.index(m)
        k_0_bound = 0
        for idx in range(k_1, -1, -1):
            if H_list[idx] >= m + Fraction(1):
                k_0_bound = idx
                break

        new_segs = list(self.segments[:k_0_bound])
        h_curr = H_list[k_0_bound]

        for idx in range(k_0_bound, k_1):
            v, l = self.segments[idx]
            dh = v[i - 1] * l
            if h_curr >= m + Fraction(1) and h_curr + dh <= m + Fraction(1):
                dh_unrefl = m + Fraction(1) - h_curr
                l_unrefl = dh_unrefl / v[i - 1]
                new_segs.append((v, l_unrefl))
                v_refl = self.algebra.reflect(v, i)
                new_segs.append((v_refl, l - l_unrefl))
                h_curr += dh
                for j in range(idx + 1, k_1):
                    v_j, l_j = self.segments[j]
                    new_segs.append((self.algebra.reflect(v_j, i), l_j))
                break
            else:
                new_segs.append((v, l))
                h_curr += dh

        new_segs.extend(self.segments[k_1:])
        return LSPath(new_segs, self.algebra)

class TensorNode(CrystalNode):
    def __init__(self, b1, b2):
        self.b1, self.b2 = b1, b2

    def __repr__(self):
        return f"({self.b1}⊗{self.b2})"

    def __hash__(self):
        return hash((self.b1, self.b2))

    def __eq__(self, other):
        return isinstance(other, TensorNode) and self.b1 == other.b1 and self.b2 == other.b2

    def wt(self):
        return tuple(x + y for x, y in zip(self.b1.wt(), self.b2.wt()))

    def eps(self, i):
        return max(self.b1.eps(i), self.b1.eps(i) + self.b2.eps(i) - self.b1.phi(i))

    def phi(self, i):
        return max(self.b2.phi(i), self.b2.phi(i) + self.b1.phi(i) - self.b2.eps(i))

    def f(self, i):
        if self.b1.phi(i) > self.b2.eps(i):
            f_b1 = self.b1.f(i)
            return TensorNode(f_b1, self.b2) if f_b1 else None
        else:
            f_b2 = self.b2.f(i)
            return TensorNode(self.b1, f_b2) if f_b2 else None

    def e(self, i):
        if self.b1.phi(i) >= self.b2.eps(i):
            e_b1 = self.b1.e(i)
            return TensorNode(e_b1, self.b2) if e_b1 else None
        else:
            e_b2 = self.b2.e(i)
            return TensorNode(self.b1, e_b2) if e_b2 else None

class MultiTensorNode(CrystalNode):
    def __init__(self, nodes):
        self.nodes = tuple(nodes)

    def __repr__(self):
        return f"({'⊗'.join(str(n) for n in self.nodes)})"

    def __hash__(self):
        return hash(self.nodes)

    def __eq__(self, other):
        return isinstance(other, MultiTensorNode) and self.nodes == other.nodes

    def wt(self):
        w = [Fraction(0)] * len(self.nodes[0].wt())
        for n in self.nodes:
            nw = n.wt()
            for idx in range(len(w)): w[idx] += nw[idx]
        return tuple(w)

    def _to_nested(self):
        res = self.nodes[-1]
        for n in reversed(self.nodes[:-1]): res = TensorNode(n, res)
        return res

    @classmethod
    def _from_nested(cls, nested_node, length):
        if length == 1: return cls((nested_node,))
        nodes = []
        curr = nested_node
        for _ in range(length - 1):
            nodes.append(curr.b1)
            curr = curr.b2
        nodes.append(curr)
        return cls(nodes)

    def f(self, i):
        f_nested = self._to_nested().f(i)
        return self._from_nested(f_nested, len(self.nodes)) if f_nested else None

    def e(self, i):
        e_nested = self._to_nested().e(i)
        return self._from_nested(e_nested, len(self.nodes)) if e_nested else None

    def eps(self, i):
        return self._to_nested().eps(i)

    def phi(self, i):
        return self._to_nested().phi(i)

class DirectSumNode(CrystalNode):
    def __init__(self, base_node, component_id, component_label=None):
        self.base_node = base_node
        self.component_id = component_id
        self.component_label = component_label if component_label else str(component_id)

    def __repr__(self): return f"[{self.component_label}]{self.base_node}"

    def __hash__(self): return hash((self.base_node, self.component_id))

    def __eq__(self, other):
        return (isinstance(other, DirectSumNode) and
                self.base_node == other.base_node and
                self.component_id == other.component_id)

    def wt(self): return self.base_node.wt()

    def eps(self, i): return self.base_node.eps(i)

    def phi(self, i): return self.base_node.phi(i)

    def f(self, i):
        target = self.base_node.f(i)
        return DirectSumNode(target, self.component_id, self.component_label) if target else None

    def e(self, i):
        target = self.base_node.e(i)
        return DirectSumNode(target, self.component_id, self.component_label) if target else None


# =====================================================================
# GENERATION & VISUALIZATION TOOLS FOR CRYSTALS
# =====================================================================

def direct_sum(crystals, labels=None):
    disjoint_union = []
    for idx, B in enumerate(crystals):
        label = labels[idx] if labels and idx < len(labels) else str(idx + 1)
        for node in B:
            disjoint_union.append(DirectSumNode(node, component_id=idx, component_label=label))
    return disjoint_union

def generate_crystal(lie_algebra, highest_weight):
    v = tuple(Fraction(c) for c in highest_weight)
    start_node = LSPath(((v, Fraction(1)),), lie_algebra)

    B_lam = []
    visited = set([start_node])
    queue = [start_node]

    while queue:
        node = queue.pop(0)
        B_lam.append(node)
        for i in lie_algebra.index_set:
            next_node = node.f(i)
            if next_node is not None and next_node not in visited:
                visited.add(next_node)
                queue.append(next_node)
    return B_lam

def get_topological_order(nodes, lie_algebra):
    G = nx.DiGraph()
    for node in nodes:
        G.add_node(node)
        for i in lie_algebra.index_set:
            target = node.f(i)
            if target is not None and target in nodes:
                G.add_edge(node, target)

    ordered_nodes = []
    components = list(nx.weakly_connected_components(G))
    components.sort(key=len, reverse=True)

    for comp in components:
        subgraph = G.subgraph(comp)
        ordered_nodes.extend(list(nx.topological_sort(subgraph)))

    return ordered_nodes

def analyze_and_draw_tensor_product(B_lam, B_mu, lie_algebra):
    lam_ordered = get_topological_order(B_lam, lie_algebra)
    mu_ordered = get_topological_order(B_mu, lie_algebra)

    x_map = {node: i for i, node in enumerate(lam_ordered)}
    y_map = {node: j for j, node in enumerate(mu_ordered)}

    G = nx.MultiDiGraph()
    tensor_nodes = [TensorNode(b1, b2) for b1 in lam_ordered for b2 in mu_ordered]

    pos = {}
    for node in tensor_nodes:
        G.add_node(node)
        pos[node] = (x_map[node.b1], len(mu_ordered) - y_map[node.b2])
        for i in lie_algebra.index_set:
            target = node.f(i)
            if target is not None and target in tensor_nodes:
                G.add_edge(node, target, label=i)

    fig, ax = plt.subplots(figsize=(16, 14))
    nx.draw_networkx_nodes(G, pos, ax=ax, node_color='whitesmoke', edgecolors='gray', node_size=700)
    labels = {n: f"{n.b1}⊗{n.b2}" for n in G.nodes()}
    nx.draw_networkx_labels(G, pos, labels, ax=ax, font_size=7, font_weight='bold')

    color_palette = ['red', 'blue', 'green', 'purple', 'orange', 'cyan']
    colors = {i: color_palette[(i - 1) % len(color_palette)] for i in lie_algebra.index_set}
    curvatures_grid = {i: (-0.2 if i % 2 == 1 else 0.2) for i in lie_algebra.index_set}
    curvatures_margin = {i: (-0.15 if i % 2 == 1 else 0.15) for i in lie_algebra.index_set}

    for i in lie_algebra.index_set:
        edges = [(u, v) for u, v, d in G.edges(data=True) if d['label'] == i]
        nx.draw_networkx_edges(G, pos, ax=ax, edgelist=edges, edge_color=colors[i],
                               arrows=True, arrowsize=15, width=1.2,
                               connectionstyle=f'arc3,rad={curvatures_grid[i]}')

    margin_offset_x = -1.5
    margin_offset_y = len(mu_ordered) + 1.5

    lam_pos = {node: (x_map[node], margin_offset_y) for node in lam_ordered}
    G_lam = nx.MultiDiGraph()
    for node in lam_ordered:
        G_lam.add_node(node)
        for i in lie_algebra.index_set:
            if node.f(i) in lam_ordered: G_lam.add_edge(node, node.f(i), label=i)

    nx.draw_networkx_nodes(G_lam, lam_pos, ax=ax, node_color='lightgreen', edgecolors='gray', node_size=600)
    nx.draw_networkx_labels(G_lam, lam_pos, {n: str(n) for n in lam_ordered}, ax=ax, font_size=8)
    for i in lie_algebra.index_set:
        edges = [(u, v) for u, v, d in G_lam.edges(data=True) if d['label'] == i]
        nx.draw_networkx_edges(G_lam, lam_pos, ax=ax, edgelist=edges, edge_color=colors[i], arrows=True,
                               connectionstyle=f'arc3,rad={curvatures_margin[i]}')

    mu_pos = {node: (margin_offset_x, len(mu_ordered) - y_map[node]) for node in mu_ordered}
    G_mu = nx.MultiDiGraph()
    for node in mu_ordered:
        G_mu.add_node(node)
        for i in lie_algebra.index_set:
            if node.f(i) in mu_ordered: G_mu.add_edge(node, node.f(i), label=i)

    nx.draw_networkx_nodes(G_mu, mu_pos, ax=ax, node_color='lightblue', edgecolors='gray', node_size=600)
    nx.draw_networkx_labels(G_mu, mu_pos, {n: str(n) for n in mu_ordered}, ax=ax, font_size=8)
    for i in lie_algebra.index_set:
        edges = [(u, v) for u, v, d in G_mu.edges(data=True) if d['label'] == i]
        nx.draw_networkx_edges(G_mu, mu_pos, ax=ax, edgelist=edges, edge_color=colors[i], arrows=True,
                               connectionstyle=f'arc3,rad={curvatures_margin[i]}')

    print("\n=== Decomposition of Tensor Product Space ===")
    components = list(nx.weakly_connected_components(G))
    irreducibles = []

    for comp in components:
        hw_nodes = [n for n in comp if all(n.e(i) is None for i in lie_algebra.index_set)]
        if hw_nodes:
            hw = hw_nodes[0]
            irreducibles.append((hw.wt(), len(comp), hw, comp))

    irreducibles.sort(key=lambda x: x[1], reverse=True)

    total_dim = 0
    for wt, dim, hw, comp in irreducibles:
        comp_x = [pos[n][0] for n in comp]
        comp_y = [pos[n][1] for n in comp]
        min_x = min(comp_x)
        max_y = max(comp_y)

        bbox_props = dict(boxstyle="round,pad=0.3", fc="ivory", ec="gray", lw=1.5, alpha=0.9)
        str_w = tuple(int(x) if x.denominator == 1 else float(x) for x in wt)
        ax.text(min_x, max_y + 0.45, rf"$HW: {str_w}$" + "\n" + rf"$\dim: {dim}$",
                fontsize=10, fontweight='bold', ha='center', va='bottom', bbox=bbox_props)

        basis_str = " + ".join([f"{str_w[i]}*w{i + 1}" for i in range(lie_algebra.rank) if str_w[i] != 0])
        if not basis_str: basis_str = "0"
        print(f"B({basis_str}) : Dimension {dim}  [Generated by {hw}]")
        total_dim += dim

    print(f"---------------------------------------------")
    print(f"Total Dimension Verified: {total_dim} = {len(B_lam)} * {len(B_mu)}\n")

    plt.title(rf"Tensor Product $B(\lambda) \otimes B(\mu)$ (Type {lie_algebra.type_name})", fontsize=16, y=1.02)
    for i in range(len(lam_ordered) + 1):
        ax.axvline(i - 0.5, color='gray', linestyle=':', alpha=0.3)
    for j in range(len(mu_ordered) + 1):
        ax.axhline(j + 0.5, color='gray', linestyle=':', alpha=0.3)

    ax.set_xlim(-2.5, len(lam_ordered))
    ax.set_ylim(0, len(mu_ordered) + 3.0)
    ax.axis('off')
    legend_patches = [mpatches.Patch(color=colors[i], label=rf'$\tilde{{f}}_{i}$') for i in lie_algebra.index_set]
    plt.legend(handles=legend_patches, loc='upper right', fontsize=12)
    plt.tight_layout()
    plt.show()

    return G

def analyze_and_draw_multi_tensor_product(crystals_list, lie_algebra):
    G = nx.MultiDiGraph()
    tensor_nodes = [MultiTensorNode(combo) for combo in itertools.product(*crystals_list)]

    for node in tensor_nodes:
        G.add_node(node)
        for i in lie_algebra.index_set:
            target = node.f(i)
            if target is not None and target in tensor_nodes:
                G.add_edge(node, target, label=i)

    components = list(nx.weakly_connected_components(G))
    components.sort(key=len, reverse=True)

    pos = {}
    x_offset = 0
    irreducibles = []

    x_spacing_multiplier = 2.5
    y_spacing_multiplier = 2.5

    for comp in components:
        subgraph = G.subgraph(comp)
        hw_nodes = [n for n in comp if all(n.e(i) is None for i in lie_algebra.index_set)]
        hw = hw_nodes[0] if hw_nodes else list(comp)[0]

        irreducibles.append((hw.wt(), len(comp), hw, comp))

        depth = {hw: 0}
        queue = [hw]
        while queue:
            curr = queue.pop(0)
            for i in lie_algebra.index_set:
                target = curr.f(i)
                if target in comp and target not in depth:
                    depth[target] = depth[curr] + 1
                    queue.append(target)

        depth_counts = {}
        for n, d in depth.items():
            depth_counts[d] = depth_counts.get(d, 0) + 1

        drawn_at_depth = {}
        comp_x_max = x_offset

        comp_ordered = sorted(list(comp), key=lambda x: str(x))
        for n in comp_ordered:
            d = depth[n]
            drawn_at_depth[d] = drawn_at_depth.get(d, 0) + 1
            w = depth_counts[d]

            x = x_offset + (drawn_at_depth[d] - (w + 1) / 2.0) * x_spacing_multiplier
            y = -d * y_spacing_multiplier
            pos[n] = (x, y)
            comp_x_max = max(comp_x_max, x)

        x_offset = comp_x_max + (x_spacing_multiplier * 1.5)

    if pos:
        all_x = [p[0] for p in pos.values()]
        all_y = [p[1] for p in pos.values()]
        min_x, max_x = min(all_x), max(all_x)
        min_y, max_y = min(all_y), max(all_y)
        fig_width = max((max_x - min_x) * 1.5, 12)
        fig_height = max((max_y - min_y) * 1.5, 12)
    else:
        fig_width, fig_height = 20, 14

    fig, ax = plt.subplots(figsize=(fig_width, fig_height))
    nx.draw_networkx_nodes(G, pos, ax=ax, node_color='white', edgecolors='none', node_size=600)

    labels = {n: str(n).replace(" ", "") for n in G.nodes()}
    bbox_props = dict(boxstyle="round,pad=0.3", fc="whitesmoke", ec="silver", lw=1)
    nx.draw_networkx_labels(G, pos, labels, ax=ax, font_size=8, font_weight='bold', bbox=bbox_props)

    color_palette = ['red', 'blue', 'green', 'purple', 'orange', 'cyan']
    colors = {i: color_palette[(i - 1) % len(color_palette)] for i in lie_algebra.index_set}

    for i in lie_algebra.index_set:
        edges = [(u, v) for u, v, d in G.edges(data=True) if d['label'] == i]
        nx.draw_networkx_edges(G, pos, ax=ax, edgelist=edges, edge_color=colors[i],
                               arrows=True, arrowsize=15, width=1.2,
                               connectionstyle='arc3,rad=0.15')

    total_dim = 0
    print(f"\n=== Decomposition of {len(crystals_list)}-Fold Tensor Product Space ===")
    for wt, dim, hw, comp in irreducibles:
        comp_x = [pos[n][0] for n in comp]
        comp_y = [pos[n][1] for n in comp]
        min_x = min(comp_x)
        max_x = max(comp_x)
        max_y = max(comp_y)
        mid_x = (min_x + max_x) / 2.0

        bbox_props_hw = dict(boxstyle="round,pad=0.4", fc="ivory", ec="gray", lw=1.5, alpha=0.9)
        str_w = tuple(int(x) if x.denominator == 1 else float(x) for x in wt)
        ax.text(mid_x, max_y + 1.5, rf"HW: {str_w}" + "\n" + rf"dim: {dim}",
                fontsize=14, fontweight='bold', ha='center', va='bottom', bbox=bbox_props_hw)

        basis_str = " + ".join([f"{str_w[i]}*w{i + 1}" for i in range(lie_algebra.rank) if str_w[i] != 0])
        if not basis_str: basis_str = "0"
        print(f"B({basis_str}) : Dimension {dim}  [Generated by {hw}]")
        total_dim += dim

    print(f"---------------------------------------------")
    expected_dim = math.prod([len(c) for c in crystals_list])
    print(f"Total Dimension Verified: {total_dim} = {expected_dim}\n")

    ax.axis('off')
    plt.title(rf"{len(crystals_list)}-Fold Tensor Product (Type {lie_algebra.type_name})", fontsize=24, y=1.02)
    legend_patches = [mpatches.Patch(color=colors[i], label=rf'$\tilde{{f}}_{i}$') for i in lie_algebra.index_set]
    plt.legend(handles=legend_patches, loc='upper right', fontsize=16)
    plt.tight_layout()

    output_filename = "tensor_decomposition.pdf"
    plt.savefig(output_filename, format="pdf", bbox_inches="tight")
    print(f"\n[!] Graph saved successfully as '{output_filename}'.")
    plt.close(fig)
    return G


# =====================================================================
# CRYSTAL MORPHISMS CLASSES
# =====================================================================

class CrystalMorphism:
    def __init__(self, domain_nodes, mapping_dict, lie_algebra):
        self.domain = list(domain_nodes)
        self.mapping = {n: mapping_dict.get(n, None) for n in domain_nodes}
        self.lie_algebra = lie_algebra

    def __call__(self, node):
        return self.mapping.get(node, None)

    def compose(self, other):
        if isinstance(other, LinearMorphism):
            return LinearMorphism(self).compose(other)

        # If the FIRST morphism is lazy, the whole chain must become lazy
        if getattr(self, 'domain', None) is None:
            return StructuralMorphism(lambda x: other(self(x)))

        # If the FIRST morphism has a fixed domain, evaluate the whole chain strictly
        new_mapping = {}
        for x in self.domain:
            fx = self(x)
            new_mapping[x] = other(fx) if fx is not None else None

        return CrystalMorphism(self.domain, new_mapping,
                               getattr(self, 'lie_algebra', getattr(other, 'lie_algebra', None)))

    def tensor(self, other):
        if isinstance(other, LinearMorphism): return LinearMorphism(self).tensor(other)
        if getattr(self, 'domain', None) is None or getattr(other, 'domain', None) is None:
            def lazy_eval(x):
                if x is None: return None
                fx = self(x.b1)
                gx = other(x.b2)
                if fx is None or gx is None: return None
                return TensorNode(fx, gx)
            return StructuralMorphism(lazy_eval)

        domain_nodes = [TensorNode(b1, b2) for b1 in self.domain for b2 in other.domain]
        new_mapping = {}
        for x in domain_nodes:
            fx = self(x.b1)
            gx = other(x.b2)
            if fx is not None and gx is not None: new_mapping[x] = TensorNode(fx, gx)
            else: new_mapping[x] = None
        return CrystalMorphism(domain_nodes, new_mapping, self.lie_algebra)

    # ===== LINEAR PROMOTION OVERLOADS =====
    def __add__(self, other): return LinearMorphism(self) + other
    def __sub__(self, other): return LinearMorphism(self) - other
    def __mul__(self, scalar): return LinearMorphism(self) * scalar
    def __rmul__(self, scalar): return self.__mul__(scalar)
    def __neg__(self): return LinearMorphism(self) * (-1)

    def __repr__(self):
        lines = [f"Crystal Morphism (Domain size: {len(self.domain)}):"]
        for d in self.domain: lines.append(f"  {d}  |--->  {self.mapping.get(d, '0')}")
        return "\n".join(lines)

class StructuralMorphism(CrystalMorphism):
    def __init__(self, mapping_func):
        self.mapping_func = mapping_func
        self.domain = None
        self.lie_algebra = None

    def __call__(self, node):
        if node is None: return None
        return self.mapping_func(node)

    def __repr__(self):
        return "[Polymorphic Structural Morphism - Evaluates Lazily]"


# =====================================================================
# 4. STRUCTURAL ISOMORPHISMS
# =====================================================================

id = StructuralMorphism(lambda x: x)
assoc = StructuralMorphism(lambda n: TensorNode(n.b1.b1, TensorNode(n.b1.b2, n.b2)))
assoc_inv = StructuralMorphism(lambda n: TensorNode(TensorNode(n.b1, n.b2.b1), n.b2.b2))
lu = StructuralMorphism(lambda n: n.b2)
ru = StructuralMorphism(lambda n: n.b1)

def get_lambda_inv(trivial_node):
    return StructuralMorphism(lambda n: TensorNode(trivial_node, n))

def get_rho_inv(trivial_node):
    return StructuralMorphism(lambda n: TensorNode(n, trivial_node))


# =====================================================================
# BUILDING PROJECTIONS/INCLUSIONS
# =====================================================================

#DANGER: The Following only works for type A as it relies on the fact that tensoring crystals of simple weights is multiplicity-free
def build_inclusion(B_in, B_out_1, B_out_2, lie_algebra):
    B_target_tensor = [TensorNode(b1, b2) for b1 in B_out_1 for b2 in B_out_2]
    hw_in = B_in[0]

    targets = [n for n in B_target_tensor if
               n.wt() == hw_in.wt() and all(n.e(m) is None for m in lie_algebra.index_set)]
    if not targets:
        raise ValueError(f"No highest weight node of weight {hw_in.wt()} found in target tensor product.")

    target_hw = targets[0]
    mapping = {hw_in: target_hw}
    queue = [hw_in]
    visited = set([hw_in])

    while queue:
        curr = queue.pop(0)
        for m in lie_algebra.index_set:
            nxt = curr.f(m)
            if nxt is not None and nxt not in visited:
                visited.add(nxt)
                mapping[nxt] = mapping[curr].f(m) if mapping[curr] is not None else None
                queue.append(nxt)

    return CrystalMorphism(B_in, mapping, lie_algebra)

def build_projection(B_in_1, B_in_2, B_target, lie_algebra):
    B_domain_tensor = [TensorNode(b1, b2) for b1 in B_in_1 for b2 in B_in_2]
    hw_target = B_target[0]

    targets = [n for n in B_domain_tensor if
               n.wt() == hw_target.wt() and all(n.e(m) is None for m in lie_algebra.index_set)]
    if not targets:
        raise ValueError(f"No highest weight node of weight {hw_target.wt()} found in domain tensor product.")

    domain_hw = targets[0]
    mapping = {n: None for n in B_domain_tensor}
    mapping[domain_hw] = hw_target
    queue = [domain_hw]
    visited = set([domain_hw])

    while queue:
        curr = queue.pop(0)
        for m in lie_algebra.index_set:
            nxt = curr.f(m)
            if nxt is not None and nxt not in visited:
                visited.add(nxt)
                mapping[nxt] = mapping[curr].f(m) if mapping[curr] is not None else None
                queue.append(nxt)

    return CrystalMorphism(B_domain_tensor, mapping, lie_algebra)


# =====================================================================
# BUILDING COMMUTORS
# =====================================================================

def build_commutor(B_i, B_j, lie_algebra):
    """
    Constructs the canonical crystal commutor isomorphism
    from B_i ⊗ B_j to B_j ⊗ B_i.
    """
    domain_nodes = [TensorNode(a, b) for a in B_i for b in B_j]
    codomain_nodes = [TensorNode(b, a) for b in B_j for a in B_i]

    # 1. Isolate the highest weight vectors of both tensor spaces
    hw_domain = [n for n in domain_nodes if all(n.e(i) is None for i in lie_algebra.index_set)]
    hw_codomain = [n for n in codomain_nodes if all(n.e(i) is None for i in lie_algebra.index_set)]

    mapping = {}
    queue = []

    # 2. Match the highest weight components by their strict weights
    for d_hw in hw_domain:
        # Since fundamental tensor products in Type A are multiplicity-free, this is unique
        matching_c_hw = next((c for c in hw_codomain if c.wt() == d_hw.wt()), None)

        if matching_c_hw is None:
            raise ValueError(f"Weight mismatch! No highest weight of wt {d_hw.wt()} found in codomain.")

        mapping[d_hw] = matching_c_hw
        queue.append(d_hw)

    visited = set(queue)

    # 3. Extend functorially to the rest of the connected components
    while queue:
        curr = queue.pop(0)
        for i in lie_algebra.index_set:
            nxt = curr.f(i)
            if nxt is not None and nxt not in visited:
                visited.add(nxt)
                # Ensure the map strictly commutes with \tilde{f}_i
                mapping[nxt] = mapping[curr].f(i)
                queue.append(nxt)

    return CrystalMorphism(domain_nodes, mapping, lie_algebra)


# =====================================================================
# LINEARIZING MORPHISMS
# =====================================================================

class FormalSum:
    """Represents a formal linear combination of Crystal Nodes (elements of the free vector space)."""

    def __init__(self, terms=None):
        self.terms = {}
        if terms:
            for node, coeff in terms.items():
                if coeff != 0:
                    self.terms[node] = self.terms.get(node, Fraction(0)) + Fraction(coeff)

    def __add__(self, other):
        res = dict(self.terms)
        for node, coeff in other.terms.items():
            new_coeff = res.get(node, 0) + coeff
            if new_coeff == 0:
                res.pop(node, None)
            else:
                res[node] = new_coeff
        return FormalSum(res)

    def __sub__(self, other):
        return self + (other * -1)

    def __mul__(self, scalar):
        return FormalSum({n: c * Fraction(scalar) for n, c in self.terms.items()})

    def __rmul__(self, scalar):
        return self.__mul__(scalar)

    def __neg__(self):
        return self.__mul__(-1)

    def __repr__(self):
        if not self.terms: return "0"
        parts = []
        for i, (node, c) in enumerate(self.terms.items()):
            if i == 0:
                if c == 1:
                    parts.append(f"{node}")
                elif c == -1:
                    parts.append(f"-{node}")
                else:
                    parts.append(f"{c}*{node}")
            else:
                if c == 1:
                    parts.append(f" + {node}")
                elif c == -1:
                    parts.append(f" - {node}")
                elif c > 0:
                    parts.append(f" + {c}*{node}")
                else:
                    parts.append(f" - {abs(c)}*{node}")
        return "".join(parts)


class LinearMorphism:
    """Promotes a strict/lazy Morphism to operate on and return FormalSums."""

    def __init__(self, base_morphism):
        self.base = base_morphism

    def __call__(self, node_or_sum):
        if node_or_sum is None: return FormalSum()

        # Extend linearly if evaluated on a FormalSum
        if isinstance(node_or_sum, FormalSum):
            res = FormalSum()
            for n, c in node_or_sum.terms.items():
                eval_n = self.base(n)
                if isinstance(eval_n, FormalSum):
                    res += eval_n * c
                elif eval_n is not None:
                    res += FormalSum({eval_n: c})
            return res
        else:
            eval_n = self.base(node_or_sum)
            if isinstance(eval_n, FormalSum): return eval_n
            if eval_n is None: return FormalSum()
            return FormalSum({eval_n: 1})

    def compose(self, other):
        other_lin = other if isinstance(other, LinearMorphism) else LinearMorphism(other)
        return LinearMorphism(StructuralMorphism(lambda x: other_lin(self(x))))

    def tensor(self, other):
        other_lin = other if isinstance(other, LinearMorphism) else LinearMorphism(other)

        def lazy_tensor_eval(x):
            if x is None: return FormalSum()
            fx = self(x.b1)
            gx = other_lin(x.b2)
            res = FormalSum()
            # Extend bilinearly
            for n1, c1 in fx.terms.items():
                for n2, c2 in gx.terms.items():
                    res += FormalSum({TensorNode(n1, n2): c1 * c2})
            return res

        return LinearMorphism(StructuralMorphism(lazy_tensor_eval))

    def __add__(self, other):
        other_lin = other if isinstance(other, LinearMorphism) else LinearMorphism(other)
        return LinearMorphism(StructuralMorphism(lambda x: self(x) + other_lin(x)))

    def __sub__(self, other):
        other_lin = other if isinstance(other, LinearMorphism) else LinearMorphism(other)
        return LinearMorphism(StructuralMorphism(lambda x: self(x) - other_lin(x)))

    def __mul__(self, scalar):
        return LinearMorphism(StructuralMorphism(lambda x: self(x) * scalar))

    def __rmul__(self, scalar):
        return self.__mul__(scalar)

    def __neg__(self):
        return self.__mul__(-1)

    def __repr__(self):
        if getattr(self.base, 'domain', None) is not None:
            lines = [f"Linear Morphism (Domain size: {len(self.base.domain)}):"]
            for d in self.base.domain: lines.append(f"  {d}  |--->  {self(d)}")
            return "\n".join(lines)
        return "[Polymorphic Linear Morphism]"


# =====================================================================
# MORPHISM EVALUATION
# =====================================================================

def generate_domain_elements(domain_tree):
    """
    Recursively generates all elements of a tensor product domain.
    domain_tree should be a list (a base crystal) or a binary tuple of sub-trees.
    Example: ((B_1, B_2), B_2) yields elements of (B_1 ⊗ B_2) ⊗ B_2.
    """
    # Base Case: It is a fundamental crystal list
    if isinstance(domain_tree, list):
        for node in domain_tree:
            yield node

    # Recursive Case: It is a tensor product of two sub-domains
    elif isinstance(domain_tree, tuple) and len(domain_tree) == 2:
        left_tree, right_tree = domain_tree
        for l_node in generate_domain_elements(left_tree):
            for r_node in generate_domain_elements(right_tree):
                yield TensorNode(l_node, r_node)
    else:
        raise ValueError("domain_tree must be a list (crystal) or a binary tuple of sub-trees.")


def evaluate_morphism(morphism, domain_tree, name=None, print_zeros=True):

    if name:
        print(f"\n[ Evaluating Morphism: {name} ]")
    print("-" * 50)

    for element in generate_domain_elements(domain_tree):
        result = morphism(element)

        # Determine if the result is "Zero" (either None or an empty FormalSum)
        if hasattr(result, 'terms'):  # It's a FormalSum
            is_zero = not bool(result.terms)
        else:  # It's a standard CrystalMorphism mapping
            is_zero = (result is None)

        if not is_zero or print_zeros:
            print(f"  {element}  |--->  {result}")


# =====================================================================
# BUILDING THE CRYSTAL A_n SPIDER GENERATING MORPHISMS
# =====================================================================

def generate_An_category(n):
    cartan = LieAlgebra(f'A{n}')

    # 1. Generate Fundamental Crystals B_0, B_1, ..., B_n
    B = {}

    # Trivial Crystal B_0
    B[0] = generate_crystal(cartan, tuple([0] * n))

    # Fundamental Crystals B_i
    for i in range(1, n + 1):
        hw = tuple([1 if k == i - 1 else 0 for k in range(n)])
        B[i] = generate_crystal(cartan, hw)

    print(f"[✓] Generated {n + 1} Fundamental Crystals (B_0 to B_{n})")

    # 2. building inverses for the left and right unitors
    trivial_hw = B[0][0]
    lu_inv = StructuralMorphism(lambda n: TensorNode(trivial_hw, n))
    ru_inv = StructuralMorphism(lambda n: TensorNode(n, trivial_hw))

    # 3. Generate Cups and Caps (i + j = 0 mod n+1)
    cup = {}
    cap = {}
    for i in range(n + 1):
        j = (n + 1 - i) % (n + 1)
        # Cup: B_0 -> B_i ⊗ B_j  (Coevaluation)
        cup[(i, j)] = build_inclusion(B[0], B[i], B[j], cartan)
        # Cap: B_i ⊗ B_j -> B_0  (Evaluation)
        cap[(i, j)] = build_projection(B[i], B[j], B[0], cartan)

    print(f"[✓] Generated {len(cup)} Cups and {len(cap)} Caps")

    # 4. Generate Canonical Inclusions and Projections (i = j + k mod n+1)
    Y = {}
    Y_bar = {}
    for j in range(n + 1):
        for k in range(n + 1):
            i = (j + k) % (n + 1)

            # Y_i^{j,k} : B_i -> B_j ⊗ B_k
            Y[(i, j, k)] = build_inclusion(B[i], B[j], B[k], cartan)

            # Y-bar_{j,k}^i : B_j ⊗ B_k -> B_i
            Y_bar[(j, k, i)] = build_projection(B[j], B[k], B[i], cartan)

    print(f"[✓] Generated {len(Y)} Canonical Inclusions (Y)")
    print(f"[✓] Generated {len(Y_bar)} Canonical Projections (Y-bar)")

    # 5. Generate Commutors (B_i ⊗ B_j -> B_j ⊗ B_i)
    comm = {}
    for i in range(n + 1):
        for j in range(n + 1):
            comm[(i, j)] = build_commutor(B[i], B[j], cartan)

    print(f"[✓] Generated {len(comm)} Commutors")
    print(f"==================================================\n")

    return cartan, B, cup, cap, Y, Y_bar, comm, lu_inv, ru_inv

# =====================================================================
# Executing Computations
# =====================================================================

if __name__ == '__main__':
    cartan, B, cup, cap, Y, Y_bar, comm, lu_inv, ru_inv = generate_An_category(3)

    f = Y[2, 1, 1].compose(Y[1, 2, 3].tensor(id)).compose(assoc).compose(id.tensor(comm[3, 1]))

    domain = B[2]
    evaluate_morphism(f, domain, 'f')

    # example: Zig-zag computation
    '''
    zig_zag = (
        lu_inv
        .compose(cup[(1, 3)].tensor(id))
        .compose(assoc)                   
        .compose(id.tensor(cap[(3, 1)]))
        .compose(ru)                      
    )
    domain_shape = (B[1])
    evaluate_morphism(zig_zag, domain_shape, "zig-zag")
    '''

    #example of crystal operation computation and visualization
    '''
    TypeB2 = LieAlgebra('B2')

    B_01 = generate_crystal(TypeB2, (0, 1))
    B_10 = generate_crystal(TypeB2, (1, 0))
    B_triv = generate_crystal(TypeB2, (0, 0))

    B_sum = direct_sum([B_01, B_triv])
    analyze_and_draw_tensor_product(B_sum,B_01, TypeB2)
    analyze_and_draw_multi_tensor_product([B_10, B_10, B_01], TypeB2)
    '''